version: '1.0'

services:
  broker:
    image: redis:latest
    container_name: broker
    networks:
      - develop

  latency-predictor:
    image: timeseries-linear-regression-service:latest
    build:
      context: services/analyze
    container_name: latency-predictor
    env_file:
      - services/analyze/.env
    volumes:
      - ${PWD}/out:/app/output
    networks:
      - develop
    command: > 
      bash -c '
        celery -A app beat & 
        celery -A app worker --loglevel=debug
      '

networks:
  develop:
    name: thesis
    external: true