version: '1.0'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks:
      - elastic

  fluentd:
    image: fluentd
    build:
      dockerfile: fluentd.Dockerfile
      context: .
    container_name: fluentd
    volumes:
      - ${PWD}/config/fluentd:/fluentd/etc
    ports:
      - "20001:20001/tcp"
    command: >
      bash -c '
        fluentd -c /fluentd/etc/fluentd.conf -v
      '
    networks:
      - elastic
    
  kibana:
    image: docker.elastic.co/kibana/kibana:${ELK_VERSION}
    container_name: kibana
    depends_on:
      - elasticsearch
    volumes:
      - ./config/kibana/kibana.keystore:/usr/share/kibana/config/kibana.keystore
    ports:
      - "5601:5601"
    environment:
      - SERVER_NAME=kibana
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - elastic
    
networks:
  elastic:
    name: thesis
    external: true
