version: '1.0'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
    container_name: elasticsearch
    # volumes:
    #   - ~/thesis/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks:
      - elk-network

  logstash:
    image: docker.elastic.co/logstash/logstash:${ELK_VERSION}
    container_name: logstash
    restart: always
    volumes:
      - ~/thesis/logstash/pipeline/pipeline.conf:/usr/share/logstash/pipeline/pipeline.conf
    # command: logstash -f /config/logstash-sample.conf 
    depends_on:
      - elasticsearch
    ports:
      - "5555:5555/udp"
      - "5044:5044"
      - "9600:9600"
      - "8080:8080"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    # volumes:
    #   - ./logstash/pipeline:/usr/share/logstash/pipeline/
    networks:
      - elk-network
    
  kibana:
    image: docker.elastic.co/kibana/kibana:${ELK_VERSION}
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    networks:
      - elk-network
  # volumes:
  # elastic_data: {}
    
networks:
  elk-network:
    external:
      name: thesis_kong-network
