version: '1.0'

services:
  broker:
    image: redis:latest
    container_name: broker
    networks:
      - predict

  predict-worker:
    image: predict-service:1.0
    build:
      context: services/predict
    container_name: predict-worker
    env_file:
      - services/predict/.env
    volumes:
      - ${PWD}/out:/app/output
    networks:
      - predict
    command: > 
      bash -c '
        celery -A app beat & 
        celery -A app worker --loglevel=debug
      '

networks:
  predict:
    name: thesis
    external: true