services:
  web:
    image: digitalocean/flask-helloworld
    container_name: web
    ports:
      - "9100:5000"
    networks:
      - service-network

networks:
  service-network:
    external:
      name: thesis_kong-network