services:
  web-5000:
    image: flask-crud
    build:
      context: services
    container_name: web-5000
    ports:
      - "9100:5000"
    networks:
      - service-network
    command: flask run --host=0.0.0.0 --port=5000
  web-5001:
    image: flask-crud
    build:
      context: services
    container_name: web-5001
    ports:
      - "9101:5001"
    networks:
      - service-network
    command: flask run --host=0.0.0.0 --port=5001
  web-5002:
    image: flask-crud
    build:
      context: services
    container_name: web-5002
    ports:
      - "9102:5002"
    networks:
      - service-network
    command: flask run --host=0.0.0.0 --port=5002
  web-5003:
    image: flask-crud
    build:
      context: services
    container_name: web-5003
    ports:
      - "9103:5003"
    networks:
      - service-network
    command: flask run --host=0.0.0.0 --port=5003

  web-5004:
    image: flask-crud
    build:
      context: services
    container_name: web-5004
    ports:
      - "9104:5004"
    networks:
      - service-network
    command: flask run --host=0.0.0.0 --port=5004

networks:
  service-network:
    external:
      name: thesis_kong-network